### ISSUE TITLE
[S7 Goliath] Negative income

### ISSUE THREAD

**Issue by nemaara** [project-ethea/Invasion_from_the_Unknown#27]
Playing on normal difficulty, S7 previously had +0 income for the whole scenario (as it's a boss battle), but now has -4 income. Perhaps either Mal Keshar or Anlinde is not being properly registered as loyal? Or perhaps there is another problem.

**Comment by Konrad22** [comment]
It's Anlinde. I noticed it now in S5.

**Comment by Konrad22** [comment]
To make the whole issue worse, every unit in this scenario seems to be declared as loyal this way. That means, if I recall or recruit units, that are not max level (and have them advance), I will walk around with a lot of negative income.

**Comment by shikadiqueen** [comment]
I believe I can work around that using objects with `duration=scenario`, assuming that's working correctly these days.

**Comment by Konrad22** [comment]
After having played S7 myself now, I can say that it is not a critical issue in S7. (While Anlinde is still a problem overall.) It doesn't matter how much gold I have when I kill the Goliath, after his defeat I will have as much gold as I had at the end of the first turn.
