### ISSUE TITLE
[S4 Over the Sands] Unarye invisible

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#33]
As it says, when Galas speaks with her, she is invisible. (She is also not added to the recall list, even though she seems to be at least somewhat important.)
[IftU-Over the Sands-Auto-Save52.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2042473/IftU-Over.the.Sands-Auto-Save52.gz)

**Comment by shikadiqueen** [comment]
Intentional.
