### ISSUE TITLE
Elvish Sorceress not healing completly upon advancing to Enchantress

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#38]
It's as if she didn't notice that is resilient.
Before
[IftU-The Source of Light-Auto-Save25.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2044434/IftU-The.Source.of.Light-Auto-Save25.gz)
After (59,31)
[IftU-The Source of Light Turn 25.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2044438/IftU-The.Source.of.Light.Turn.25.gz)

**Comment by shikadiqueen** [comment]
It seems there's something weird going on with `wesnoth.transform_unit` as used by the [event](https://github.com/project-ethea/Invasion_from_the_Unknown/blob/master/lua/Invasion_from_the_Unknown.lua#L243) that replaces the Elvish Enchantress with [Elvish Enchantress 2](https://github.com/project-ethea/Invasion_from_the_Unknown/blob/master/units/elves-wood/Enchantress.cfg).

**Comment by sevu** [comment]
If using ADVANCE_UNIT (which uses [modify_unit]type=) one must heal the unit afterwards, at least it was in 1.12 already so. With [transform_unit]… who knows

**Comment by sevu** [comment]
Although, the case I meant is about the unit advancing to having more HP, while here it is about the trait…

**Comment by Vultraz** [comment]
Not relevant anymore since 2eda5c9.
