### ISSUE TITLE
[S10] Volcanic Underground

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#39]
Why is the Volcanic underground 'time' a cycle of 8 with no changes?

**Comment by shikadiqueen** [comment]
Could you provide a save showing this? It's certainly a single ToD in the WML.

**Comment by Konrad22** [comment]
[IftU-The Source of Light-Auto-Save44.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2046321/IftU-The.Source.of.Light-Auto-Save44.gz)
Select any unit in the volcanic part of the map to see the local 'time of day'.

**Comment by shikadiqueen** [comment]
Oh right. That'd be this:

https://github.com/project-ethea/Invasion_from_the_Unknown/blob/master/macros/schedules.cfg#L19

**Comment by Konrad22** [comment]
Cool. :D
