### ISSUE TITLE
[S12/13] Lichs

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#41]
Why do Lichs count as minions of Mal Keshar? They have their own will after all...

**Comment by adramolokh** [comment]
This is [intentional](https://github.com/project-ethea/Invasion_from_the_Unknown/blob/63c8238e7155529085adb578df9b499059137858/scenarios/12_The_Escape.cfg#L1012).

**Comment by adramolokh** [comment]
The explanation works well enough for me: 'most undead minions' implies the ones that you don't recruit through context, and liches fall under the umbrella of 'undead', so it would be more logical to assume that liches are given to Anlinde than staying with the main party.

What stands out to you as nonsensical?

**Comment by Konrad22** [comment]
That (kinda selfish) beings, that have decided to die so they can live forever, decide to do a suicided commando.
The other undead minions do not have a choice, they are bound by their summoner and lack a free will, unlike the lichs.

**Comment by shikadiqueen** [comment]
I don't feel this is something that needs to be explicitly addressed in prose, honestly.

**Comment by Konrad22** [comment]
But they decide to sacrifice their live for the fleeing elves and dwarves. D: And noone thanks them. :(
