### ISSUE TITLE
[S13 Face your Fate] eternally shrouded(?) hex

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#43]
3,4 is a Road (Flat) hex which is black, as if it is shrouded. You can move on this hex, but you can't dispell the shroud.

**Comment by shikadiqueen** [comment]
Completely intentional. Features like this can be found elsewhere in both IftU and AtS and they signify areas that aren't part of the scenario but still exist in some way.
