### ISSUE TITLE
[S13 Face your Fate] Defeating the Chaos Warlord forever

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#44]
They way the scenario is I can defeat the Chaos Warlord as many times as I want to. It's not about me losing the scenario, it's about me losing patience with the scenario and suiciding, which is kinda not a good way to end a scenario. :(

**Comment by Konrad22** [comment]
[IftU-Face your Fate-Auto-Save52.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2046324/IftU-Face.your.Fate-Auto-Save52.gz)
I gave up on or two turns earlier after defeating the Chaos Warlord for the third time.

**Comment by shikadiqueen** [comment]
Would you prefer if the player could no longer recruit units after the first time the Warlord is taken down?

**Comment by Konrad22** [comment]
Huh. Hm. No.
How about a hidden event that triggers at 25? 30? turns, with the Warlord losing patience and striking somehow a heavy, possibly fatal blow at Anlinde. Anlinde reacts with blowing the cavern up.
The same thing could happen when you kill the Warlord a second time.

That way the scenario will end when you play defensive (you won't be able to stall forever) and it will end if you play aggressive, managing to kill the warlord a second time.

**Comment by shikadiqueen** [comment]
The situation is supposed to rapidly become hopeless. I'd rather not have players be able stall for too long since otherwise they're just going to complain that the scenario allows them to waste their time.

**Comment by Konrad22** [comment]
This can be closed, right, since you destroy all my units anyway.
