### ISSUE TITLE
Erathan (Aragwaithi Strongbow) with wrong introduction

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#45]
His unit is introduced as Archer that is supplementing his skills with a glaive in melee combat, which is not true.
Archers, Strongbows and Greatbows use daggers, short swords and swords respectively. Only Slayers are using a glaive.

**Comment by shikadiqueen** [comment]
Actually,
```
"<b>Erathan</b> is an <b>Aragwaith Strongbow</b>. His skill with the bow is not as great as that of elvish archers, but he aspires to either improve it or enhance his ability with melee weapons such as the glaive. Nonetheless, he is not used to fighting in open fields, so be careful when deciding where he should attack from!
```
This refers to the branching nature of the Aragwaith Strongbow's advancements.

**Comment by Konrad22** [comment]
Ohhh. My mistake. Sorry.
