### ISSUE TITLE
Elynia flying skills

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#46]
Why is Elynia worse at flying than the other faries? Is that for balancing purposes?

**Comment by shikadiqueen** [comment]
She's not. Her MP is 6, whereas the base MP for the Faerie Sprite line is 5 (the Forest Spirit, an undead unit, being the exception with 6) and the Elvish Shyde and Sylph's base MP is 6.

**Comment by Konrad22** [comment]
Elynia/Sprite MP cost:
Swamp: 2/1
Deep water 4/2
Shallow Water 2/1
Coastal Reef 2/1

Which is why I'm saying that Elynia is wose at flying than the other faries. She doesn't lose out in base speed. Just in navigating.
