### ISSUE TITLE
Elynia Abilites with commas

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#47]
I sure you can see what I'm talking about. I'll try to dig up relevant github entries/forum posts.
![elynia](https://user-images.githubusercontent.com/39015360/40631775-0610b6c4-62e0-11e8-9bfb-85702a720aa0.png)

**Comment by Konrad22** [comment]
https://github.com/wesnoth/wesnoth/issues/3060

**Comment by shikadiqueen** [comment]
The upstream bug will be fixed in Wesnoth 1.14.14 and 1.15.4.
