### ISSUE TITLE
[S19 Under the Sands] Some Matrix Flow Systems (lvl0 unit) have a ZoC

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#51]
35,52 and 35,54
[IftU-Under the Sands-Auto-Save50.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2047523/IftU-Under.the.Sands-Auto-Save50.gz)

39,49 and 39,50
[IftU-Under the Sands-Auto-Save51.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2047525/IftU-Under.the.Sands-Auto-Save51.gz)

If that's intended behavior, then it would be nice to drop some hints about it. It is very unexpected.

**Comment by shikadiqueen** [comment]
It is intentional. I don't think it merits any exposition in-game, though.
