### ISSUE TITLE
[S20 The Heart] wrong/different lose conditions

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#53]
Galas lose conditions:
Death of Elynia/Mal Keshar/Erathan (looks like everyone is fine with Galas/Althurin dying)

Althurin lose condition:
Death of Althurin (everybody else can die, right?)

**Comment by shikadiqueen** [comment]
Intentional. Both sides have different objectives here and most of the time they won't be able to do anything to protect each other.

**Comment by Konrad22** [comment]
But...that does mean those lose conditions are wrong/incomplete. D:
