### ISSUE TITLE
[22A Face the Enemy] How is Mal Keshar supposed to destroy the exit gate? (fatal bug maybe?)

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#55]
So, Elynia is 'incapacitated' and now I'm trying to destroy the exit gate. But how do I do that? I'm standing next to it with Mal Keshar and nothing happens. Right now I can only wait until my time runs out and then die. :(
[IftU-Face of the Enemy-Auto-Save31.gz](https://github.com/project-ethea/Invasion_from_the_Unknown/files/2048119/IftU-Face.of.the.Enemy-Auto-Save31.gz)

**Comment by Konrad22** [comment]
Looking at the code long and hard...I guess something with setting up the doors didn't went wrong? (line 923)

**Comment by shikadiqueen** [comment]
This has already been fixed for a couple of days, actually. I just need to fix some of the issues you've reported and release a new snapshot.

**Comment by Konrad22** [comment]
So...you won't give me a hotfix so I can continue playing? :(

**Comment by shikadiqueen** [comment]
You can install the latest version of the door setup code from Naia:
https://github.com/project-ethea/Naia/blob/aae2687a38a32ea7a5c565e8ae5e923fe514024c/lua/common.lua

It needs to go into `Invasion_from_the_Unknown/Naia/lua/common.lua`. You may need to start the scenario over in *some* cases of the bug (this isn't the only one).
