### ISSUE TITLE
Nothing happens after killing Goliath

### ISSUE THREAD

**Issue by AncientGeneral** [project-ethea/Invasion_from_the_Unknown#56]
Version 1.14.2
In scenario Goliath I killed boss and didn't win. There was an error message related to lua.
I don't see any way to complete this mission honestly.
![_2018-05-29_21-57-55](https://user-images.githubusercontent.com/20964929/40679520-0f374590-638c-11e8-94cc-0a9cae3f52ae.png)

**Comment by shikadiqueen** [comment]
This apparently can only happen if you don't have mainline's music installed (some Linux distributions like Debian and Ubuntu provide the option). Reported to the devs.

**Comment by AncientGeneral** [comment]
I have mainline's music installed (steam version) and have not IftU_Music.

**Comment by shikadiqueen** [comment]
wesnoth/wesnoth#3194 is fixed in 1.14.3 now, so closing this.
