### ISSUE TITLE
[23B Until Death] ellipses not found in turn 4

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#60]
Galas and Mal Keshar got turned. (This does not happen when Erathan and Mal Keshar are turned.)
![image](https://user-images.githubusercontent.com/39015360/40717605-3f87c414-640d-11e8-9e9f-223c9a48bb85.png)

**Comment by shikadiqueen** [comment]
That's a screenshot of turn 1.

Let me guess, the error involves Galas' ellipse?

**Comment by Konrad22** [comment]
..oops. I'll be right back with the right screenshot.

I don't know what that means. :/

**Comment by shikadiqueen** [comment]
You can check for the exact missing image path in [Wesnoth's stderr](https://forums.wesnoth.org/viewtopic.php?f=4&t=46166).

**Comment by Konrad22** [comment]
![grafik](https://user-images.githubusercontent.com/39015360/40742631-6cfb451e-644f-11e8-91a5-476b96c9ee5b.png)
For now, I've had this happen instead. She is missing her team circle. :(

**Comment by Konrad22** [comment]
And I've got 
Create an empty image
Create an empty image
around the time I reported the initial issue.
