### ISSUE TITLE
[S23B Until Death] 'incomplete' lose conditions

### ISSUE THREAD

**Issue by Konrad22** [project-ethea/Invasion_from_the_Unknown#62]
Argan can recruit Cockatrices, therefor Elynia can be petrified, which would make me lose as well. The lose conditions do not account for that.

**Comment by shikadiqueen** [comment]
She cannot be petrified though.

**Comment by Konrad22** [comment]
Uh. Why? She could be petrified in 23A (and I did lose that way once). What changed?

**Comment by shikadiqueen** [comment]
If she's petrified in S23B she will instantly undo it, and the first time she will say something about it.

**Comment by Konrad22** [comment]
Okay. ^^ Would you mind adding a note about that in the scenario objectives? Otherwise the player will(should) do anything he can to avoid the possibility of her getting petrified, even if it means makeing sacrifices. 
And it's not unlikely that someone will report that missing lose condition if he or she manages to get through that scenario without Elynia getting petrified.

**Comment by shikadiqueen** [comment]
I generally do not like going into detail about every single special gameplay mechanic, especially during boss battles and when it involves story elements. I don't think it's a problem if the player avoids the Cockatrices (they will waste Elynia's attack regardless) and I don't think it's a problem to point people back here if the question comes up again in the future. :)
