### ISSUE TITLE
[S2, A Real Confrontation] Game scrolls to Ledinor upon demon recruitment event

### ISSUE THREAD

**Issue by adramolokh** [project-ethea/Invasion_from_the_Unknown#64]
Minor.
Upon recruiting a demon, Ledinor says a line of dialogue. Unfortunately, the player cannot see this refers to the demon immediately as the UI immediately focuses on Ledinor, who is at the other side of the battlefield.

**Comment by shikadiqueen** [comment]
There's a 750 milliseconds time window where the game focuses on the demon before Lédinor speaks. Does this not work over there or is it not sufficiently long time to see the unit?

**Comment by adramolokh** [comment]
Not sufficiently long enough time.
